services:
  - type: web
    name: nids-rf
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python train_model.py
    startCommand: gunicorn app:app
