services:
  - type: web
    name: nids-rf
    env: python
    pythonVersion: "3.11.0"
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python train_model.py
    startCommand: gunicorn app:app